### ISSUE TITLE
bcdl incompatible with custom domains

### ISSUE THREAD

**Issue by koocieyu** [daot/bcdl#6] opened 2021-11-07 03:35 UTC
Some artists use custom domains for their bandcamp page but bcdl is not able to handle them. ([example](https://3six.net/album/indigo-expanse))

![image](https://user-images.githubusercontent.com/26856087/140631347-eb23a548-aed1-488a-9a89-800956cbab5c.png)

**Comment by steamyalt** [comment] 2022-01-27 21:25
Can confirm.
This is caused by the validateLink function checking if its a *.bandcamp.com link.
Fixing this would require a more sophisticated validation function

**Comment by daot** [comment] 2023-02-17 07:07
should be fixed! a while later haha

**Closed by daot** 2023-02-17 07:07 UTC
